# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.16"
src = "src"
test = "test"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4
